import { idToVarName, sortTokens, tokenValueToString } from "./shared.js";

export function formatCss(tokens, { brand, mode }) {
  const lines = [];
  lines.push(`:root[data-brand="${brand}"][data-mode="${mode}"] {`);
  for (const token of sortTokens(tokens)) {
    lines.push(`  --${idToVarName(token.id)}: ${tokenValueToString(token)};`);
  }
  lines.push("}");
  lines.push("");
  lines.push("/* Generated by @prismforge/token-build */");
  return lines.join("\n");
}


