import { idToSnakeName, sortTokens, tokenValueToString } from "./shared.js";

function swiftEscape(text) {
  return String(text).replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

export function formatIos(tokens, { brand, mode }) {
  const lines = [];
  lines.push("// Generated by @prismforge/token-build");
  lines.push(`// brand: ${brand}, mode: ${mode}`);
  lines.push("import Foundation");
  lines.push("");
  lines.push("public enum PrismForgeTokens {");
  for (const token of sortTokens(tokens)) {
    const name = idToSnakeName(token.id);
    const value = swiftEscape(tokenValueToString(token));
    lines.push(`    public static let ${name} = "${value}"`);
  }
  lines.push("}");
  return lines.join("\n");
}


